/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBankRouteImport } from './routes/_app/bank'
import { Route as AppCryptoRouteImport } from './routes/_app/crypto'
import { Route as AppDcdsRouteImport } from './routes/_app/dcds'
import { Route as AppEtfRouteImport } from './routes/_app/etf'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppTplusRouteImport } from './routes/_app/tplus'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppCryptoRoute = AppCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => AppRoute,
} as any)
const AppDcdsRoute = AppDcdsRouteImport.update({
  id: '/dcds',
  path: '/dcds',
  getParentRoute: () => AppRoute,
} as any)
const AppEtfRoute = AppEtfRouteImport.update({
  id: '/etf',
  path: '/etf',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppTplusRoute = AppTplusRouteImport.update({
  id: '/tplus',
  path: '/tplus',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/bank': typeof AppBankRoute
  '/crypto': typeof AppCryptoRoute
  '/dcds': typeof AppDcdsRoute
  '/etf': typeof AppEtfRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/stock': typeof AppStockRoute
  '/tplus': typeof AppTplusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bank': typeof AppBankRoute
  '/crypto': typeof AppCryptoRoute
  '/dcds': typeof AppDcdsRoute
  '/etf': typeof AppEtfRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/stock': typeof AppStockRoute
  '/tplus': typeof AppTplusRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bank': typeof AppBankRoute
  '/_app/crypto': typeof AppCryptoRoute
  '/_app/dcds': typeof AppDcdsRoute
  '/_app/etf': typeof AppEtfRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/tplus': typeof AppTplusRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bank'
    | '/crypto'
    | '/dcds'
    | '/etf'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/tplus'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bank'
    | '/crypto'
    | '/dcds'
    | '/etf'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/tplus'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/bank'
    | '/_app/crypto'
    | '/_app/dcds'
    | '/_app/etf'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/stock'
    | '/_app/tplus'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank': {
      id: '/_app/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crypto': {
      id: '/_app/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof AppCryptoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dcds': {
      id: '/_app/dcds'
      path: '/dcds'
      fullPath: '/dcds'
      preLoaderRoute: typeof AppDcdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/etf': {
      id: '/_app/etf'
      path: '/etf'
      fullPath: '/etf'
      preLoaderRoute: typeof AppEtfRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tplus': {
      id: '/_app/tplus'
      path: '/tplus'
      fullPath: '/tplus'
      preLoaderRoute: typeof AppTplusRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBankRoute: typeof AppBankRoute
  AppCryptoRoute: typeof AppCryptoRoute
  AppDcdsRoute: typeof AppDcdsRoute
  AppEtfRoute: typeof AppEtfRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStockRoute: typeof AppStockRoute
  AppTplusRoute: typeof AppTplusRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBankRoute: AppBankRoute,
  AppCryptoRoute: AppCryptoRoute,
  AppDcdsRoute: AppDcdsRoute,
  AppEtfRoute: AppEtfRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStockRoute: AppStockRoute,
  AppTplusRoute: AppTplusRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
